### ISSUE TITLE
Non inclusive language

### ISSUE THREAD

**Issue by jordanrule** [hmason/tc#6]
I noticed heavy usage of the terms `blacklist` and `whitelist` in this project.  Removal of these biased terms is something some of us have invested quite a lot of effort into, so it is discouraging to see it heavily in use in such a high profile project like `tc`. (https://chromium.googlesource.com/chromium/src/+/master/styleguide/inclusive_code.md#racially-neutral)

Would it be possible to change these terms to `blocklist` and `allowlist`?  I would be happy to PR if the author is otherwise predisposed.

**Comment by hmason** [comment]
This isn't an active project or actively used, but I do support the vocabulary change!
